output   = "my_models"
wipe     = true
no-tests = true
add-enum-types = true

[mysql]
  dbname  = "test"
  host    = "localhost"
  port    = 3306
  user    = "root"
  pass    = "123456"
  sslmode = "false"
  tinyint_as_int = true
